### ISSUE TITLE
Error on redirect FilamentManager::getUserName()

### ISSUE THREAD

**Issue by danielreales7** [stechstudio/filament-impersonate#60]
When redirect I'm getting this error:

Filament\FilamentManager::getUserName(): Argument #1 ($user) must be of type Illuminate\Database\Eloquent\Model|Illuminate\Contracts\Auth\Authenticatable, null given, called in /Users/daniel/Desktop/Proyectos/tickify/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 353

`<x-filament-impersonate::banner/>`

**Comment by danielreales7** [comment]
I solved with: `Impersonate::make()->guard('users')`

**Comment by thethunderturner** [comment]
> I solved with: `Impersonate::make()->guard('users')`

Hey, care to give more information? I still have the same error:

```php
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make("name"),
                TextColumn::make("email"),
            ])
            ->filters([
                //
            ])
            ->actions([
                Impersonate::make()->guard('users'),
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }
```

**Comment by dennisoderwald** [comment]
I have the same problem. The login itself works, but when I go back to the url of the other Guard, this error appears. So it seems that I can't be logged into 2 Guard's at the same time.
